### ISSUE TITLE
第三集错别字

### ISSUE THREAD

**Issue by echopan** [xzczd/InfiniteRyvius#1]
```
Dialogue: 0,0:00:10.40,0:00:11.30,Default,,0,0,0,,真伪鳝\N{\fs7}\N{\fs14}ぎぜんしゃ
```

伪善

**Comment by xzczd** [comment]
上传到github以来第一个反馈，感动！……不过这个地方其实是故意的，因为日文台词没有使用汉字，而是使用了假名，当然了，这个台词也是日本观众听写的，严格说来没啥权威性，但从剧情上来说这个处理很合理……啊你是不是还没看后边？那这里就先不细谈了。总之，当时翻译的时候考虑过3种方案：

1. 无视这个细节，直接用”伪善“
2.  用拼音
3. 用同音错字

最后反复权衡后用了方案3。

我在《说明》部分解释一下吧。
